name: pluseplay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  on_audio_query: ^2.9.0
  curved_navigation_bar: ^1.0.6
  just_audio: ^0.9.37
  audioplayers: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.1.1
  hive_generator: ^2.0.1
  build_runner: ^2.1.0
  # flutter_launcher_icons: ^0.14.1

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "lib/assets/images/file.png"

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/splashScreen.jpg
    - lib/assets/images/shortwave.jpeg
    - lib/assets/images/believer.jpeg
    - lib/assets/images/shapeofu.jpeg
    - lib/assets/images/chainsmokers.jpg
    - lib/assets/images/eminem.webp
    - lib/assets/images/download.jpeg
    - lib/assets/images/file.png
